# Reference: http://docs.travis-ci.com/user/languages/perl/

dist: xenial
sudo: false
language: perl
perl: "5.22"

branches:
  only:
    - develop
    - master

addons:
  apt:
    packages:
    - samtools
    - tabix
    - bcftools
    - zlib1g-dev
    - libarchive-zip-perl
    - libdbd-mysql-perl
    - libdbi-perl
    - libmodule-build-perl
    - libtest-simple-perl

env:
  - VEP_VERSION=95.3

before_install:
  - rsync rsync://ftp.ensembl.org/ensembl/pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz data/
  - gzip -d data/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz
  - bgzip data/Homo_sapiens.GRCh38.dna.chromosome.13.fa

install:
  - wget -P $HOME https://github.com/Ensembl/ensembl-vep/archive/release/${VEP_VERSION}.tar.gz
  - tar -zxf $HOME/${VEP_VERSION}.tar.gz -C $HOME
  - mv $HOME/ensembl-vep-release-${VEP_VERSION} $HOME/vep
  - perl $HOME/vep/INSTALL.pl --NO_UPDATE --AUTO a --DESTDIR $HOME/vep

script:
  - perl tests/vcf2maf.t
