# Reference: http://docs.travis-ci.com/user/languages/perl/

dist: bionic
sudo: false
language: perl
perl: "5.26"
services: docker

branches:
  only:
    - master

before_install:
  - docker build -t vcf2maf:master .
  - docker image prune -f
  - rsync rsync://ftp.ensembl.org/ensembl/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz tests/
  - gzip -d tests/Homo_sapiens.GRCh38.dna.chromosome.13.fa.gz

script:
  - perl tests/vcf2maf.t
